SET search_path = public;

-- --------------------------------------------------
-- JOB TITLES
-- --------------------------------------------------
INSERT INTO job_title (job_title) VALUES
('Professor'),
('Lektor'),
('Adjunkt'),
('Administratör'),
('Doktorand'),
('TA'),
('Senior Lektor');

-- --------------------------------------------------
-- DEPARTMENTS (10) - manager_employee_id NULL for now
-- --------------------------------------------------
INSERT INTO department (department_name, manager_employee_id) VALUES
('EECS', NULL),
('CBH', NULL),
('SCI', NULL),
('MATH', NULL),
('INF', NULL),
('BIO', NULL),
('CHEM', NULL),
('PHYS', NULL),
('HUM', NULL),
('BUS', NULL);

-- --------------------------------------------------
-- PERSON (100 rows) - identity PKs generated by DB
-- --------------------------------------------------
INSERT INTO person (personal_number, first_name, last_name, phone_number, address) VALUES
('19900101-0001','Anna','Svensson','0701000001','Teknikringen 1, Stockholm'),
('19900202-0002','Erik','Johansson','0701000002','Lindstedtsvägen 2, Stockholm'),
('19900303-0003','Maria','Lindberg','0701000003','Valhallavägen 3, Stockholm'),
('19900404-0004','Karl','Andersson','0701000004','Hantverkargatan 4, Stockholm'),
('19900505-0005','Sara','Nilsson','0701000005','Sveavägen 5, Stockholm'),
('19900606-0006','Oskar','Berg','0701000006','Frescativägen 6, Stockholm'),
('19900707-0007','Eva','Lund','0701000007','Karlavägen 7, Stockholm'),
('19900808-0008','Jonas','Pettersson','0701000008','Kungsgatan 8, Stockholm'),
('19900909-0009','Lina','Eriksson','0701000009','Kungsholmen 9, Stockholm'),
('19901010-0010','Mikael','Olsson','0701000010','Östermalm 10, Stockholm'),
('19901111-0011','Anton','Wester','0701000011','Drottninggatan 11, Stockholm'),
('19901212-0012','Linda','Fors','0701000012','Brunnsgatan 12, Stockholm'),
('19901301-0013','Fred','Hansson','0701000013','Regeringsgatan 13, Stockholm'),
('19901402-0014','Karin','Nyström','0701000014','Sveavägen 14, Stockholm'),
('19901503-0015','Tobias','Gustafsson','0701000015','Norrtullsgatan 15, Stockholm'),
('19901604-0016','Emma','Bergström','0701000016','Valhallavägen 16, Stockholm'),
('19901705-0017','Patrik','Anders','0701000017','Hantverkargatan 17, Stockholm'),
('19901806-0018','Nina','Lind','0701000018','Teknikringen 18, Stockholm'),
('19901907-0019','Simon','Strand','0701000019','Lindstedtsvägen 19, Stockholm'),
('19902008-0020','Ola','Hult','0701000020','Karlavägen 20, Stockholm'),
('19902109-0021','Maja','Pettersson','0701000021','Kungsgatan 21, Stockholm'),
('19902210-0022','Henrik','Svensson','0701000022','Kungsholmen 22, Stockholm'),
('19902311-0023','Sofia','Lindqvist','0701000023','Östermalm 23, Stockholm'),
('19902412-0024','Jakob','Axelsson','0701000024','Drottninggatan 24, Stockholm'),
('19902501-0025','Therese','Berg','0701000025','Brunnsgatan 25, Stockholm'),
('19902602-0026','Marcus','Linde','0701000026','Regeringsgatan 26, Stockholm'),
('19902703-0027','Julia','Söder','0701000027','Sveavägen 27, Stockholm'),
('19902804-0028','Anders','Ljung','0701000028','Norrtullsgatan 28, Stockholm'),
('19902905-0029','Ann','Gunnarsson','0701000029','Valhallavägen 29, Stockholm'),
('19903006-0030','Per','Hansson','0701000030','Hantverkargatan 30, Stockholm'),
('19903107-0031','Lina','Fransson','0701000031','Teknikringen 31, Stockholm'),
('19903208-0032','Erica','Norberg','0701000032','Lindstedtsvägen 32, Stockholm'),
('19903309-0033','Magnus','Hedlund','0701000033','Karlavägen 33, Stockholm'),
('19903410-0034','Ida','Wallin','0701000034','Kungsgatan 34, Stockholm'),
('19903511-0035','Jon','Sjöberg','0701000035','Kungsholmen 35, Stockholm'),
('19903612-0036','Alva','Nyberg','0701000036','Östermalm 36, Stockholm'),
('19903701-0037','Gustav','Eklund','0701000037','Drottninggatan 37, Stockholm'),
('19903802-0038','Sara','Björk','0701000038','Brunnsgatan 38, Stockholm'),
('19903903-0039','Peter','Lindahl','0701000039','Regeringsgatan 39, Stockholm'),
('19904004-0040','Anna','Karlsson','0701000040','Sveavägen 40, Stockholm'),
('19904105-0041','David','Borg','0701000041','Norrtullsgatan 41, Stockholm'),
('19904206-0042','Camilla','Fröberg','0701000042','Valhallavägen 42, Stockholm'),
('19904307-0043','Erik','Möller','0701000043','Hantverkargatan 43, Stockholm'),
('19904408-0044','Lotta','Ivarsson','0701000044','Teknikringen 44, Stockholm'),
('19904509-0045','Henrietta','Bengtsson','0701000045','Lindstedtsvägen 45, Stockholm'),
('19904610-0046','Olof','Stenberg','0701000046','Karlavägen 46, Stockholm'),
('19904711-0047','Mona','Svedberg','0701000047','Kungsgatan 47, Stockholm'),
('19904812-0048','Kjell','Nord','0701000048','Kungsholmen 48, Stockholm'),
('19904913-0049','Lena','Åkesson','0701000049','Östermalm 49, Stockholm'),
('19905014-0050','Philip','Rosén','0701000050','Drottninggatan 50, Stockholm'),
('19905115-0051','Karin','Olsson','0701000051','Brunnsgatan 51, Stockholm'),
('19905216-0052','Björn','Larsson','0701000052','Regeringsgatan 52, Stockholm'),
('19905317-0053','Nora','Malm','0701000053','Sveavägen 53, Stockholm'),
('19905418-0054','Viktor','Hansson','0701000054','Norrtullsgatan 54, Stockholm'),
('19905519-0055','Mikaela','Åberg','0701000055','Valhallavägen 55, Stockholm'),
('19905620-0056','Robin','Sjöström','0701000056','Hantverkargatan 56, Stockholm'),
('19905721-0057','Therese','Bergman','0701000057','Teknikringen 57, Stockholm'),
('19905822-0058','Oskar','Nilsson','0701000058','Lindstedtsvägen 58, Stockholm'),
('19905923-0059','Mats','Hammar','0701000059','Karlavägen 59, Stockholm'),
('19906024-0060','Erna','Sahl','0701000060','Kungsgatan 60, Stockholm'),
('19906125-0061','Jonas','Lindström','0701000061','Kungsholmen 61, Stockholm'),
('19906226-0062','Agnes','Bergqvist','0701000062','Östermalm 62, Stockholm'),
('19906327-0063','Hampus','Lind','0701000063','Drottninggatan 63, Stockholm'),
('19906428-0064','Klara','Sundström','0701000064','Brunnsgatan 64, Stockholm'),
('19906529-0065','Stefan','Jonas','0701000065','Regeringsgatan 65, Stockholm'),
('19906630-0066','Cecilia','Palm','0701000066','Sveavägen 66, Stockholm'),
('19906731-0067','Isak','Åkerman','0701000067','Norrtullsgatan 67, Stockholm'),
('19906832-0068','Miriam','Wester','0701000068','Valhallavägen 68, Stockholm'),
('19906933-0069','Elias','Nordström','0701000069','Hantverkargatan 69, Stockholm'),
('19907034-0070','Helena','Gustafson','0701000070','Teknikringen 70, Stockholm'),
('19907135-0071','Ola','Byström','0701000071','Lindstedtsvägen 71, Stockholm'),
('19907236-0072','Zara','Rosen','0701000072','Karlavägen 72, Stockholm'),
('19907337-0073','Mattias','Hedman','0701000073','Kungsgatan 73, Stockholm'),
('19907438-0074','Signe','Nyqvist','0701000074','Kungsholmen 74, Stockholm'),
('19907539-0075','Leif','Åhman','0701000075','Östermalm 75, Stockholm'),
('19907640-0076','Aina','Håkansson','0701000076','Drottninggatan 76, Stockholm'),
('19907741-0077','Rikard','Forsberg','0701000077','Brunnsgatan 77, Stockholm'),
('19907842-0078','Lova','Eriksson','0701000078','Regeringsgatan 78, Stockholm'),
('19907943-0079','Timo','Larsen','0701000079','Sveavägen 79, Stockholm'),
('19908044-0080','Bianca','Vik','0701000080','Norrtullsgatan 80, Stockholm'),
('19908145-0081','Göran','Lindell','0701000081','Valhallavägen 81, Stockholm'),
('19908246-0082','Malin','Åsberg','0701000082','Hantverkargatan 82, Stockholm'),
('19908347-0083','Rona','Kero','0701000083','Teknikringen 83, Stockholm'),
('19908448-0084','Andreas','Kjell','0701000084','Lindstedtsvägen 84, Stockholm'),
('19908549-0085','Sigrid','Holmgren','0701000085','Karlavägen 85, Stockholm'),
('19908650-0086','Torbjörn','Ek','0701000086','Kungsgatan 86, Stockholm'),
('19908751-0087','Noah','Stark','0701000087','Kungsholmen 87, Stockholm'),
('19908852-0088','Mona','Söderberg','0701000088','Östermalm 88, Stockholm'),
('19908953-0089','Klara','Lindström','0701000089','Drottninggatan 89, Stockholm'),
('19909054-0090','Dennis','Hult','0701000090','Brunnsgatan 90, Stockholm'),
('19909155-0091','Rita','Sten','0701000091','Regeringsgatan 91, Stockholm'),
('19909256-0092','Vera','Lindqvist','0701000092','Sveavägen 92, Stockholm'),
('19909357-0093','Bertil','Åberg','0701000093','Norrtullsgatan 93, Stockholm'),
('19909458-0094','Irene','Lindström','0701000094','Valhallavägen 94, Stockholm'),
('19909559-0095','Sven','Olofsson','0701000095','Hantverkargatan 95, Stockholm'),
('19909660-0096','Lena','Mårtensson','0701000096','Teknikringen 96, Stockholm'),
('19909761-0097','Hugo','Nygren','0701000097','Lindstedtsvägen 97, Stockholm'),
('19909862-0098','Elsa','Svensson','0701000098','Karlavägen 98, Stockholm'),
('19909963-0099','Aron','Blom','0701000099','Kungsgatan 99, Stockholm'),
('19910064-0100','Mira','Hansson','0701000100','Kungsholmen 100, Stockholm');

-- --------------------------------------------------
-- EMPLOYEES (60 rows) - reference person rows above
-- Note: manager_id NULL initially where top-level managers will be set eventually
-- --------------------------------------------------
INSERT INTO employee (skill_set, person_id, job_id, manager_id, department_id) VALUES
('Databases, SQL',(SELECT person_id FROM person WHERE personal_number='19900101-0001'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Programming, Java',(SELECT person_id FROM person WHERE personal_number='19900202-0002'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Web Development',(SELECT person_id FROM person WHERE personal_number='19900303-0003'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Mathematics',(SELECT person_id FROM person WHERE personal_number='19900404-0004'),(SELECT job_id FROM job_title WHERE job_title='Professor'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('AI, ML',(SELECT person_id FROM person WHERE personal_number='19900505-0005'),(SELECT job_id FROM job_title WHERE job_title='Professor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Networks',(SELECT person_id FROM person WHERE personal_number='19900606-0006'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Algorithms',(SELECT person_id FROM person WHERE personal_number='19900707-0007'),(SELECT job_id FROM job_title WHERE job_title='Professor'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('Teaching Support',(SELECT person_id FROM person WHERE personal_number='19900808-0008'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Information Systems',(SELECT person_id FROM person WHERE personal_number='19900909-0009'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Project Management',(SELECT person_id FROM person WHERE personal_number='19901010-0010'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='BUS')),
('Data Analysis',(SELECT person_id FROM person WHERE personal_number='19901111-0011'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='BIO')),
('Systems Design',(SELECT person_id FROM person WHERE personal_number='19901212-0012'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='CHEM')),
('Cybersecurity',(SELECT person_id FROM person WHERE personal_number='19901301-0013'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='HUM')),
('Advanced Math',(SELECT person_id FROM person WHERE personal_number='19901402-0014'),(SELECT job_id FROM job_title WHERE job_title='Professor'),NULL,(SELECT department_id FROM department WHERE department_name='PHYS')),
('Data Eng',(SELECT person_id FROM person WHERE personal_number='19901503-0015'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Embedded',(SELECT person_id FROM person WHERE personal_number='19901604-0016'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Software Testing',(SELECT person_id FROM person WHERE personal_number='19901705-0017'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('UX',(SELECT person_id FROM person WHERE personal_number='19901806-0018'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Sys Admin',(SELECT person_id FROM person WHERE personal_number='19901907-0019'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Cloud',(SELECT person_id FROM person WHERE personal_number='19902008-0020'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('DB Admin',(SELECT person_id FROM person WHERE personal_number='19902109-0021'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Backend',(SELECT person_id FROM person WHERE personal_number='19902210-0022'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Mobile Dev',(SELECT person_id FROM person WHERE personal_number='19902311-0023'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Research',(SELECT person_id FROM person WHERE personal_number='19902412-0024'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Quantum',(SELECT person_id FROM person WHERE personal_number='19902501-0025'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='PHYS')),
('Lecturer',(SELECT person_id FROM person WHERE personal_number='19902602-0026'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('ML Research',(SELECT person_id FROM person WHERE personal_number='19902703-0027'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Networks II',(SELECT person_id FROM person WHERE personal_number='19902804-0028'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Archivist',(SELECT person_id FROM person WHERE personal_number='19902905-0029'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('Teaching Support 2',(SELECT person_id FROM person WHERE personal_number='19903006-0030'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Lectures',(SELECT person_id FROM person WHERE personal_number='19903107-0031'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Testing 2',(SELECT person_id FROM person WHERE personal_number='19903208-0032'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Tutoring',(SELECT person_id FROM person WHERE personal_number='19903309-0033'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Lecturer II',(SELECT person_id FROM person WHERE personal_number='19903410-0034'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Systems',(SELECT person_id FROM person WHERE personal_number='19903511-0035'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Analysis',(SELECT person_id FROM person WHERE personal_number='19903612-0036'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Researcher 2',(SELECT person_id FROM person WHERE personal_number='19903701-0037'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Admin',(SELECT person_id FROM person WHERE personal_number='19903802-0038'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('Teaching Aid',(SELECT person_id FROM person WHERE personal_number='19903903-0039'),(SELECT job_id FROM job_title WHERE job_title='TA'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Course Dev',(SELECT person_id FROM person WHERE personal_number='19904004-0040'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Research X',(SELECT person_id FROM person WHERE personal_number='19904105-0041'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Systems 2',(SELECT person_id FROM person WHERE personal_number='19904206-0042'),(SELECT job_id FROM job_title WHERE job_title='Adjunkt'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('Lab Tech',(SELECT person_id FROM person WHERE personal_number='19904307-0043'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('TA 2',(SELECT person_id FROM person WHERE personal_number='19904408-0044'),(SELECT job_id FROM job_title WHERE job_title='TA'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Instructor',(SELECT person_id FROM person WHERE personal_number='19904509-0045'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Data Eng 2',(SELECT person_id FROM person WHERE personal_number='19904610-0046'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='INF')),
('Research 3',(SELECT person_id FROM person WHERE personal_number='19904711-0047'),(SELECT job_id FROM job_title WHERE job_title='Doktorand'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('Admin 2',(SELECT person_id FROM person WHERE personal_number='19904812-0048'),(SELECT job_id FROM job_title WHERE job_title='Administratör'),NULL,(SELECT department_id FROM department WHERE department_name='MATH')),
('TA 3',(SELECT person_id FROM person WHERE personal_number='19904913-0049'),(SELECT job_id FROM job_title WHERE job_title='TA'),NULL,(SELECT department_id FROM department WHERE department_name='EECS')),
('Lecturer 3',(SELECT person_id FROM person WHERE personal_number='19905014-0050'),(SELECT job_id FROM job_title WHERE job_title='Lektor'),NULL,(SELECT department_id FROM department WHERE department_name='INF'));

-- --------------------------------------------------
-- Now set department managers (update to real employee ids)
-- We pick some employees inserted above to be managers
-- --------------------------------------------------
UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19900101-0001'))
  WHERE department_name = 'EECS';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19900505-0005'))
  WHERE department_name = 'CBH';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19900707-0007'))
  WHERE department_name = 'SCI';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19900404-0004'))
  WHERE department_name = 'MATH';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19900909-0009'))
  WHERE department_name = 'INF';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19901111-0011'))
  WHERE department_name = 'BIO';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19901212-0012'))
  WHERE department_name = 'CHEM';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19901402-0014'))
  WHERE department_name = 'PHYS';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19901301-0013'))
  WHERE department_name = 'HUM';

UPDATE department SET manager_employee_id =
  (SELECT employee_id FROM employee WHERE person_id = (SELECT person_id FROM person WHERE personal_number = '19901010-0010'))
  WHERE department_name = 'BUS';

-- --------------------------------------------------
-- SALARY HISTORY (versions) - references employees that now exist
-- --------------------------------------------------
INSERT INTO salary_history (salary_amount, version, employee_id) VALUES
(58000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900101-0001'))),
(40000, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900101-0001'))),
(55000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900202-0002'))),
(57000, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900202-0002'))),
(54000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900303-0003'))),
(55500, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900303-0003'))),
(60000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900404-0004'))),
(62000, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900404-0004'))),
(65000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900505-0005'))),
(67500, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900505-0005'))),
(52000, 1, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900606-0006'))),
(54000, 2, (SELECT employee_id FROM employee WHERE person_id=(SELECT person_id FROM person WHERE personal_number='19900606-0006')));

-- --------------------------------------------------
-- TEACHING ACTIVITY
-- --------------------------------------------------
INSERT INTO teaching_activity (activity_name, factor) VALUES
('Lecture', 3.6),
('Lab', 2.4),
('Tutorial', 2.4),
('Seminar', 1.8),
('Examination', 1.0),
('Administration', 1.0),
('Other', 1.0);

-- --------------------------------------------------
-- TEACHING LIMIT
-- --------------------------------------------------
INSERT INTO teaching_limit (max_courses) VALUES (4);

-- --------------------------------------------------
-- COURSE LAYOUTS (example set, with versions)
-- --------------------------------------------------
INSERT INTO course_layout (course_code, course_name, min_students, max_students, hp, version) VALUES
('IV1351','Data Storage Paradigms',50,250,15,1),
('IV1351','Data Storage Paradigms',50,250,7.5,2),
('IV1351','Data Storage Paradigms',50,250,6,3),
('IX1500','Discrete Mathematics',50,150,7.5,1),
('IX1500','Discrete Mathematics',50,150,7.5,2),
('CS1010','Intro to CS',20,120,7.5,1),
('CS1010','Intro to CS',20,130,6,2),
('MA1000','Calculus I',10,200,7.5,1),
('CS3000','Advanced Databases',8,60,15,1),
('EN1050','Electronics',10,60,6.0,1),
('EE2000','Embedded Systems',8,50,7.5,1),
('AI1010','Intro AI',10,100,7.5,1),
('DB2010','Databases II',10,80,7.5,1),
('SW3000','Software Engineering',12,150,7.5,1),
('DP2100','Data Processing',10,60,7.5,1),
('CS4000','Machine Learning',10,80,7.5,1);

-- --------------------------------------------------
-- COURSE INSTANCES (sample)
-- --------------------------------------------------
INSERT INTO course_instance (num_students, study_period, study_year, course_layout_id) VALUES
(200,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='IV1351' AND version=2 LIMIT 1)),
(150,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='IX1500' AND version=1 LIMIT 1)),
(130,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='IX1500' AND version=1 LIMIT 1)),
(120,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='CS1010' AND version=1 LIMIT 1)),
(130,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='CS1010' AND version=2 LIMIT 1)),
(40,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='EN1050' AND version=1 LIMIT 1)),
(100,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='IV1351' AND version=1 LIMIT 1)),
(95,'P3',2026,(SELECT course_layout_id FROM course_layout WHERE course_code='IV1351' AND version=2 LIMIT 1)),
(180,'P3',2026,(SELECT course_layout_id FROM course_layout WHERE course_code='MA1000' AND version=1 LIMIT 1)),
(50,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='EN1050' AND version=1 LIMIT 1)),
(40,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='EE2000' AND version=1 LIMIT 1)),
(90,'P4',2026,(SELECT course_layout_id FROM course_layout WHERE course_code='AI1010' AND version=1 LIMIT 1)),
(70,'P4',2026,(SELECT course_layout_id FROM course_layout WHERE course_code='DB2010' AND version=1 LIMIT 1)),
(130,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='SW3000' AND version=1 LIMIT 1)),
(50,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='DP2100' AND version=1 LIMIT 1)),
(80,'P2',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='CS3000' AND version=1 LIMIT 1)),
(70,'P1',2025,(SELECT course_layout_id FROM course_layout WHERE course_code='CS4000' AND version=1 LIMIT 1));


-- --------------------------------------------------
-- --------------------------------------------------
-- PLANNED ACTIVITY (safe inserts)
-- --------------------------------------------------
-- Skapa planerade aktiviteter för alla kursinstanser och alla teaching_activity
-- Justera hours per activity som exempel
INSERT INTO planned_activity (planned_hours, course_instance_id, teaching_activity_id) VALUES
(78, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(55, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(40, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(66, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')), 
(82, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(67, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IX1500' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(70, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IX1500' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(44, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IX1500' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(69, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IX1500' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(64, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IX1500' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(45, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS1010' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(75, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS1010' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(28, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS1010' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(45, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS1010' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(94, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS1010' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(72, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='MA1000' AND ci.study_period='P3' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(38, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='MA1000' AND ci.study_period='P3' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(50, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='MA1000' AND ci.study_period='P3' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(30, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='MA1000' AND ci.study_period='P3' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(25, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='MA1000' AND ci.study_period='P3' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(80, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS3000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(80, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS3000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(60, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS3000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(45, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS3000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(40, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS3000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(68, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EN1050' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(52, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EN1050' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(36, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EN1050' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(44, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EN1050' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(28, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EN1050' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(75, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EE2000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(58, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EE2000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(41, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EE2000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(50, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EE2000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(32, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='EE2000' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(77, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='AI1010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(49, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='AI1010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(56, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='AI1010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(35, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='AI1010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(29, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='AI1010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(82, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DB2010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(60, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DB2010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(44, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DB2010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(52, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DB2010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(38, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DB2010' AND ci.study_period='P4' AND ci.study_year=2026 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(70, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='SW3000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(48, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='SW3000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(55, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='SW3000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(33, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='SW3000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(27, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='SW3000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(73, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DP2100' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(57, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DP2100' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(39, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DP2100' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(47, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DP2100' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(31, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='DP2100' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(85, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS4000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(50, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS4000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(62, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS4000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(42, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS4000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(34, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='CS4000' AND ci.study_period='P1' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other')),
(78, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lecture')),
(60, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Lab')),
(65, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Seminar')),
(40, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Tutorial')),
(30, (SELECT course_instance_id FROM course_instance ci JOIN course_layout cl ON ci.course_layout_id=cl.course_layout_id WHERE cl.course_code='IV1351' AND ci.study_period='P2' AND ci.study_year=2025 LIMIT 1), (SELECT teaching_activity_id FROM teaching_activity WHERE activity_name='Other'));

INSERT INTO allocation (planned_activity_id, employee_id, allocated_hours)
SELECT 
    pa.planned_activity_id,
    sh.employee_id,
    ROUND(pa.planned_hours * (0.9 + random() * 0.3))  -- 90–120% of planned hours
FROM planned_activity pa
-- Pick only employees that have a salary (latest version if needed)
JOIN (
    SELECT employee_id
    FROM salary_history
    WHERE version = 1  -- optional: pick latest salary version
) sh ON true
ORDER BY random();  -- optional: shuffle so allocations are random

